### ISSUE TITLE
Some parameters are not resolved correctly

### ISSUE THREAD

**Issue by PuzzledFace** [openpharma/autoquarto#5]
With this YAML header
```
---
title: "Parameter Test"
format: html
editor: visual
params:
  dataName: mtcars
  rowCount: NA
  x: wt
  y: mpg
  g: cyl
  plotTitle: This is a title for the plot
---
```

running this code

```
data %>%
  ggplot() +
    geom_point(
      aes(
        x=get(params$x),
        y=get(params$y),
        group=get(params$g)
      )
    ) +
    labs(
      title=params$plotTitle,
      x=params$x,
      y=params$y
    ) +
    theme_light()
```

produces
![image](https://user-images.githubusercontent.com/52156249/223077196-2489f414-800c-4a86-865b-8978cd578845.png)

the same happens with
```
... group=!! {{ params$g }} ...
```

and

```
... group=get(!! {{ params$g }}) ...
```
